microservice:
  localstorage: ./tmp
  
filestorage:
  path: ./data

rabbitmq:
  host: localhost
  port: 15672
  username: guest
  password: password
  
  video_queue: video_queue
  transcription_queue: transcription_queue
  translation_queue: translation_queue
  tts_queue: tts_queue
  status_queue: status_queue 
  mount_queue: mount_queue 
  subtitles_queue: subtitles_queue 

mongodb:
  host: localhost
  port: 27017
  username: root
  password: password
  
  database: audub
  video_collection: videos
  voice_collection: voices

ollama:
  host:  localhost