filestorage:
  path: ./data/
rabbitmq:
  host: 172.20.0.3
  port: 15672
  username: guest
  password: password
  
  job_queue: job_queue
  status_queue: status_queue 

mongodb:
  host: 172.20.0.2
  port: 27017
  username: root
  password: password
  
  database: audub
  collection: videos
