microservice:
  localstorage: ./tmp
  
filestorage:
  path: /data/

rabbitmq:
  host: 172.20.0.3
  port: 15672
  username: guest
  password: password
  
  video_queue: video_queue
  transcription_queue: transcription_queue
  translation_queue: translation_queue
  tts_queue: tts_queue
  status_queue: status_queue 

mongodb:
  host: 172.20.0.2
  port: 27017
  username: root
  password: password
  
  database: audub
  video_collection: videos
  voice_collection: voices

ollama:
  host:  172.20.0.10